import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Comp/Navbar";
import NavS from "@/components/Comp/NavS";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" text-white w-full h-full dark ">
        <Navbar />

        {children}
      </body>
    </html>
  );
}
